config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index' # add this line
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  after_update_commit { broadcast_append_to 'todos' }

  validates :title, presence: true
  
  enum status: { incomplete: 0, complete: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.in_order_of(:status, %w[incomplete complete])
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)
  
    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
  
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_item") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTurboTodos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %> 
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2>
        <%= pluralize(todo.errors.count, "error") %> prohibited this todo from being
        saved:
      </h2>

      <ul>
        <% todo.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: "sr-only" %>
    <div class="relative">
      <%= form.text_field :title, class: "block shadow-sm rounded-full border
      border-gray-200 outline-none px-6 py-4 w-full focus:border-sky-300
      focus:outline-none focus:ring-4 focus:ring-sky-50 text-lg
      placeholder:text-gray-400", placeholder: "Add a new todo" %>

      <div class="absolute top-0 right-0">
        <%= form.submit class: "mt-px rounded-full py-4 px-5 bg-sky-500 text-white
        font-medium cursor-pointer border-2 border-sky-500 hover:bg-sky-600
        hover:border-sky-600" %>
      </div>
    </div>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li id="<%= "#{dom_id(todo)}_item" %>" class="py-3">
  <%= turbo_frame_tag dom_id(todo) do %>
    <div class="flex items-center justify-between">
      <%= link_to todo.title, edit_todo_path(todo), class: "flex-1 #{"line-through opacity-50" if todo.complete?}" %>

      <div class="flex items-center space-x-3">
        <% if todo.complete? %>
          <%= button_to "Mark incomplete", todo_path(todo, todo: { status: 'incomplete'}), method: :patch, class: "bg-neutral-50 px-3 py-2 rounded inline-flex items-center justify-center text-neutral-600" %>
        <% else %>
          <%= button_to "Mark complete", todo_path(todo, todo: { status: 'complete'}), method: :patch, class: "bg-green-50 px-3 py-2 rounded inline-flex items-center justify-center text-green-600" %>
        <% end %>

        <%= button_to "Delete", todo_path(todo), method: :delete, class: "bg-red-50 px-3 py-2 rounded inline-flex items-center justify-center text-red-600" %>
      </div>
    </div>
  <% end %>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %> 
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<div class="w-full">
  <div class="mb-6">
    <h1 class="font-bold text-4xl">Turbo Tasks</h1>
  </div>

  <%= render "form", todo: Todo.new %>

  <%= turbo_stream_from "todos" %>
  <div id="todos" class="divide-y list-none">
    <%= render @todos %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>